# Log file
log_file_path: "app.log"

# Redis configuration
redis_addr: "149.126.169.135:6379"
redis_pass: "p1cky8eimer"
redis_db: 3

# RabbitMQ configuration
rmq_addr: "149.126.169.135:5672"
rmq_user: "admin"
rmq_pass: "p1cky8eimer"
rmq_queue: "queryMailSignUp"

# SMTP configuration
smtp_server: "mail.eastern-gate.ru"
smtp_port: "587"
smtp_username: "hello"
smtp_password: "NovoBlack88"
smtp_mail: "hello@eastern-gate.ru"